Staging (#215)
* - Bump Version

* - Bump Version (#214)

diff --git a/.github/workflows/soc-packs-release-v2.yml b/.github/workflows/soc-packs-release-v2.yml
--- a/.github/workflows/soc-packs-release-v2.yml
+++ b/.github/workflows/soc-packs-release-v2.yml
@@ -43,16 +43,16 @@ jobs:
           python-version: "3.10"
 
       - name: Install demisto-sdk
-        run: pip install "demisto-sdk==${DEMISTO_SDK_VERSION}"
+        run: pip install "demisto-sdk==${{ env.DEMISTO_SDK_VERSION }}"
 
-      - name: Verify demisto-sdk version
-        run: |
-          VER=$(demisto-sdk --version | grep -Eo '([0-9]+\.)+[0-9]+' | head -1)
-          echo "SDK version = $VER"
-          if [ "$VER" != "${DEMISTO_SDK_VERSION}" ]; then
-            echo "ERROR: Expected demisto-sdk ${DEMISTO_SDK_VERSION}"
-            exit 1
-          fi
+      #- name: Verify demisto-sdk version
+      #  run: |
+      #    VER=$(demisto-sdk --version | grep -Eo '([0-9]+\.)+[0-9]+' | head -1)
+      #    echo "SDK version = $VER"
+      #    if [ "$VER" != "${{ env.DEMISTO_SDK_VERSION }}" ]; then
+      #      echo "ERROR: Expected demisto-sdk ${{ env.DEMISTO_SDK_VERSION }}"
+      #      exit 1
+      #    fi
 
       ###################################################################
       # Discover all packs
